DEFAULT_VIEWPORT_HEIGHT = 430
DEFAULT_VIEWPORT_WIDTH = 360

# MAIN APP
APP_NAME = "SnapToExcel"
APP_VERSION = "0.0.1"
APP_RELEASE_TYPE = "Beta"
APP_AUTHOR = "Abu Ghalib"
APP_AUTHOR_EMAIL = "abughalib64@gmail.com"
APP_TITLE_TEXT = "ScreenShot to Excel"
PRIMARY_WINDOW_TAG = "Primary Window"
APP_SMALL_ICON_PATH = "icon.ico"
APP_LARGE_ICON_PATH = "icon.ico"
APP_TRANSPARENCY = 1
BUTTON_ICON_HEIGHT = 60
BUTTON_ICON_WIDTH = 55
DEFAULT_UI_UPDATE_DELAY = 1
DEFAULT_MAX_TITLE_LEN = 150
MAX_LABEL_WIDTH = 18
DEFAULT_TEXT_FIELD_WIDTH = 40
DEFAULT_TEXT_AREA_WIDTH = 40
DEFAULT_TEXT_AREA_HEIGHT = 10
DEFAULT_FONT_FAMILY = "Calibri"
DEFAULT_FONT_SIZE = 16
DEFAULT_TEXT_FIELD_INDENT = 130
DEFAULT_FONT_NAME = "Roboto-Regular.ttf"
EZSNAP_DL = "abughalib64@gmail.com"
COPYRIGHT_TEXT = "© Classic EZSnap Team"
APP_BUILD_DATE = "2024-02-12 21:01:14.770205"

# CHILD WINDOW
DEFAULT_CHILD_WITH = 200
DEFAULT_CHILD_HEIGHT = 500

# LAST ACTION CHILD WINDOW
LAST_ACTION_TITLE = "Last Five Actions"
IMAGE_THUMBNAIL_SIZE_1080P = (480, 300)
IMAGE_THUMBNAIL_SIZE_1200P = (480, 270)
CHILD_MAX_FIELD_WIDTH = 480

# SECONDARY WINDOW
CHANGE_SHORTCUT_WINDOW_TITLE = "Change Shortcut Key"
CHANGE_SHORTCUT_TEXTAREA_LABEL = "Press Any Key you want to use."
CHANGE_SHORTCUT_DEFAULT_VIEWPORT_HEIGHT = 100
CHANGE_SHORTCUT_DEFAULT_VIEWPORT_WIDTH = 300

# DEFAULT PASS VALUE
DEFAULT_SHEET_NAME = "Sheet1"
DEFAULT_INFO_MESSAGE = ""

# MENU

HELP_MENU_LABEL = "Help"

HELP_MENU_VIDEO_LABEL = "Watch Demo Video"

HELP_MENU_DOCUMENTATION_LABEL = "Checkout Documentation"

HELP_MENU_CHECK_UPDATE = "Check For Update"

HELP_MENU_ABOUT_LABEL = "About"

# FIELDS
# FILE
FILE_NAME_LABEL = "File Name:"
FILE_NAME_LABEL_HINT = "Enter File Name: "
FILE_NAME_SOURCE = "file_name"

# FOLDER LOCATION
FOLDER_LOCATION_LABEL = "Folder Location: "
FOLDER_LOCATION_LABEL_HINT = "Where do you want to Save?"
FOLDER_LOCATION_SOURCE = "folder_location"

# START CELL POSITION

START_CELL_POSITION_LABEL = "Start Cell Position: "
START_CELL_POSITION_HINT = "Start from which cell in Excel"
START_CELL_POSITION_SOURCE = "position_source"

# ROW SPERATION

ROW_SEPERATION_LABEL = "Row Seperation: "
ROW_SEPERATION_HINT = "Vertical space between each Image"
ROW_SEPERATION_SOURCE = "row_seperation"

# SHEET NAME
SHEET_NAME_LABEL = "Sheet Name: "
SHEET_NAME_HINT = "Worksheet Name: "
SHEET_SOURCE = "sheet_name"

# DB CREDENTIALS
DB_USERNAME_LABEL = "DB User Name: "
DB_PASSWORD_LABEL = "DB Password: "
DB_CONNECTION_URL_LABEL = "Connection URL: "

# INFO TEXT
INFO_TEXT_LABEL = "Info: "

# Shortcut Key Label
CURRENT_SHORTCUT_KEY_LABEL = "Current Shortcut Key: "
CHANGE_SHORTCUT_ICON = "change_shortcutkey_button.png"

# BUTTONS
# SQL QUERY BUTTON
SQL_QUERY_EXECUTE_BUTTON_LABEL = "Execute SQL & Store"
SQL_EXECUTE_BUTTON_ICON = "execute_sql_button.png"

# CHANGE SHEET
CHANGE_SHEET_BUTTON_LABEL = "Change Sheet"
CHANGE_SHEET_BUTTON_LABEL_CHANGED = "Sheet Changed"
CHANGE_SHEET_BUTTON_LABEL_FAILED = "Failed"
CHANGE_SHEET_BUTTON_ICON = "sheet_change.png"

# UNDO LAST ACTION
UNDO_LAST_ACTION_LABEL = "Undo Last Action"
UNDO_BUTTON_ICON = "undo_button.png"

# START_BUTTON
START_BUTTON_LABEL = "Let's Snap"
START_BUTTON_ICON = "start_button.png"
STOP_BUTTON_LABEL = "Stop"
STOP_BUTTON_ICON = "stop_button.png"

# CHANGE SHORTCUT KEY
CHANGE_SHORTCUT_KEY_BUTTON_LABEL = "Change Shortcut Key"

# STYLE
STYLE_INFO_LABEL = "info.TLabel"
STYLE_WARNING_LABEL = "warning.TLabel"
STYLE_ERROR_LABEL = "error.TLabel"

# LINKS
HELP_DOCS_VIDEO = "https://www.github.com/abughalib"
HELP_DOCS_LINK = "https://www.github.com/abughalib"
UPDATE_LINK_DOCS = "https://www.github.com/abughalib"

# INFO TYPE
INFO = "INFO"
SUCCESS = "SUCCESS"
WARNING = "WARNING"
ERROR = "ERROR"